---
- hosts: all

  become: yes
  tasks:


# Setting up Docker
  - name: install prerequisites
    block:
      - name: installing apt packages
        apt:
          name:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg-agent
            - software-properties-common
          update_cache: yes
    rescue:
        - name: wait for server
          pause:
            minutes: 1

        - name: installing apt packages
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg-agent
              - software-properties-common
            update_cache: yes

  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable

  - name: install docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes

  - name: add userpermissions
    shell: "usermod -aG docker vagrant"


# Installing Python Docker SDK
  - name: install python package manager
    apt:
      name: python3-pip

  - name: install python sdk
    become_user: "vagrant"
    pip:
      name:
        - docker
        - docker-compose

# Restarting the machine
  - name: Restarting the server
    ansible.builtin.reboot:

# Configuring portainer
  - name: Create directory
    file:
      path: /home/vagrant/portainer-data
      state: directory

  - name: Deploy Portainer
    become_user: "vagrant"
    community.docker.docker_container:
      name: portainer
      image: "docker.io/portainer/portainer-ce"
      ports:
        - "9443:9443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /home/vagrant/portainer-data:/data
      restart_policy: always